//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM2_1_1min_POD23
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> POD43_PT_G { get; set; }
        public Nullable<double> POD43_FT_G { get; set; }
        public Nullable<double> POD43_LT1_BR { get; set; }
        public Nullable<double> POD43_LT2_BR { get; set; }
        public Nullable<double> POD43_BR_AVG_TEMP { get; set; }
        public Nullable<double> POD43_LT1_RP { get; set; }
        public Nullable<double> POD43_LT2_RP { get; set; }
        public Nullable<double> POD43_P_RP_SPEED_REFERENCE { get; set; }
        public Nullable<double> POD43_BC { get; set; }
        public Nullable<double> POD43_MT { get; set; }
        public Nullable<double> HMI_DATALOG_P_A43 { get; set; }
    }
}
