//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLMD_24Hour_Table_2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> OC1 { get; set; }
        public Nullable<double> GF { get; set; }
        public Nullable<double> GCHP { get; set; }
        public Nullable<double> ECHP { get; set; }
        public Nullable<double> MODBUS_COGEN_TODAYKWH_ACT { get; set; }
        public Nullable<double> MODBUS_COGEN_TOTALHRS_ACT { get; set; }
    }
}
