//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOLD_24Hour_Table_1
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> EV3 { get; set; }
        public Nullable<double> EV4 { get; set; }
        public Nullable<double> MF3 { get; set; }
        public Nullable<double> MF4 { get; set; }
        public Nullable<double> VC4_DAILY_LOG { get; set; }
        public Nullable<double> VC5_DAILY_LOG { get; set; }
        public Nullable<double> VC6_DAILAY_LOG { get; set; }
        public Nullable<double> VC7_DAILAY_LOG { get; set; }
        public Nullable<double> CPLE { get; set; }
        public Nullable<double> MODBUS_COGEN_TOTALKWH_ACT { get; set; }
        public Nullable<double> MODBUS_COGEN_TOTALHRS_ACT { get; set; }
    }
}
