//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Data.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOLD_1Hour_Table_2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> TT_L1_1_EU { get; set; }
        public Nullable<double> TT_L1_2_EU { get; set; }
        public Nullable<double> TT_L1_3_EU { get; set; }
        public Nullable<double> TT_L1_4_EU { get; set; }
        public Nullable<double> TT_L2_1_EU { get; set; }
        public Nullable<double> TT_L2_2_EU { get; set; }
        public Nullable<double> TT_L2_3_EU { get; set; }
        public Nullable<double> TT_L2_4_EU { get; set; }
    }
}
