//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class affinitydev1Entities : DbContext
    {
        public affinitydev1Entities()
            : base("name=affinitydev1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CalcDate> CalcDates { get; set; }
        public virtual DbSet<TotalKw> TotalKws { get; set; }
        public virtual DbSet<vDM2_1_1min_Central> vDM2_1_1min_Central { get; set; }
        public virtual DbSet<vDM2_1_1min_POD21> vDM2_1_1min_POD21 { get; set; }
        public virtual DbSet<vDM2_1_1min_POD22> vDM2_1_1min_POD22 { get; set; }
        public virtual DbSet<vDM2_1_1min_POD23> vDM2_1_1min_POD23 { get; set; }
        public virtual DbSet<vDM2_1_1min_POD24> vDM2_1_1min_POD24 { get; set; }
        public virtual DbSet<vDM2_1_24hour_Central> vDM2_1_24hour_Central { get; set; }
        public virtual DbSet<vDM2_1_24hour_Central_2> vDM2_1_24hour_Central_2 { get; set; }
        public virtual DbSet<vDM4_3_1min_Central> vDM4_3_1min_Central { get; set; }
        public virtual DbSet<vDM4_3_1min_POD34> vDM4_3_1min_POD34 { get; set; }
        public virtual DbSet<vDM4_3_1min_POD35> vDM4_3_1min_POD35 { get; set; }
        public virtual DbSet<vDM4_3_1min_POD41> vDM4_3_1min_POD41 { get; set; }
        public virtual DbSet<vDM4_3_1min_POD42> vDM4_3_1min_POD42 { get; set; }
        public virtual DbSet<vDM4_3_1min_POD43> vDM4_3_1min_POD43 { get; set; }
        public virtual DbSet<vDM4_3_1min_POD44> vDM4_3_1min_POD44 { get; set; }
        public virtual DbSet<vDM4_3_24hour_Central> vDM4_3_24hour_Central { get; set; }
        public virtual DbSet<vDM4_3_24hour_Central_2> vDM4_3_24hour_Central_2 { get; set; }
        public virtual DbSet<vFGO_1Hour_Table_1> vFGO_1Hour_Table_1 { get; set; }
        public virtual DbSet<vFGO_1Minute_Table1> vFGO_1Minute_Table1 { get; set; }
        public virtual DbSet<vFGO_1Minute_Table2> vFGO_1Minute_Table2 { get; set; }
        public virtual DbSet<vFGO_24Hour_Table1> vFGO_24Hour_Table1 { get; set; }
        public virtual DbSet<vFGO_24Hour_Table2> vFGO_24Hour_Table2 { get; set; }
        public virtual DbSet<vLMD_1Hour_Table_1> vLMD_1Hour_Table_1 { get; set; }
        public virtual DbSet<vLMD_1Hour_Table_2> vLMD_1Hour_Table_2 { get; set; }
        public virtual DbSet<vLMD_1Minute_Table_1> vLMD_1Minute_Table_1 { get; set; }
        public virtual DbSet<vLMD_24Hour_Table_1> vLMD_24Hour_Table_1 { get; set; }
        public virtual DbSet<vLMD_24Hour_Table_2> vLMD_24Hour_Table_2 { get; set; }
        public virtual DbSet<vOLD_1Hour_Table_1> vOLD_1Hour_Table_1 { get; set; }
        public virtual DbSet<vOLD_1Hour_Table_2> vOLD_1Hour_Table_2 { get; set; }
        public virtual DbSet<vOLD_1Minute_Table_1> vOLD_1Minute_Table_1 { get; set; }
        public virtual DbSet<vOLD_24Hour_Table_1> vOLD_24Hour_Table_1 { get; set; }
        public virtual DbSet<vOLD_24Hour_Table_2> vOLD_24Hour_Table_2 { get; set; }
        public virtual DbSet<InsertedLog> InsertedLogs { get; set; }
    
        public virtual int myUpdDataSP(Nullable<int> myyearParam)
        {
            var myyearParamParameter = myyearParam.HasValue ?
                new ObjectParameter("myyearParam", myyearParam) :
                new ObjectParameter("myyearParam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myUpdDataSP", myyearParamParameter);
        }
    
        public virtual int GetKws()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetKws");
        }
    
        public virtual ObjectResult<sp_vDM2_1_1min_Central_Result> sp_vDM2_1_1min_Central()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_1min_Central_Result>("sp_vDM2_1_1min_Central");
        }
    
        public virtual ObjectResult<sp_vDM2_1_1min_POD21_Result> sp_vDM2_1_1min_POD21()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_1min_POD21_Result>("sp_vDM2_1_1min_POD21");
        }
    
        public virtual ObjectResult<sp_vDM2_1_1min_POD22_Result> sp_vDM2_1_1min_POD22()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_1min_POD22_Result>("sp_vDM2_1_1min_POD22");
        }
    
        public virtual ObjectResult<sp_vDM2_1_1min_POD23_Result> sp_vDM2_1_1min_POD23()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_1min_POD23_Result>("sp_vDM2_1_1min_POD23");
        }
    
        public virtual ObjectResult<sp_vDM2_1_1min_POD24_Result> sp_vDM2_1_1min_POD24()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_1min_POD24_Result>("sp_vDM2_1_1min_POD24");
        }
    
        public virtual ObjectResult<sp_vDM2_1_24hour_Central_Result> sp_vDM2_1_24hour_Central()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_24hour_Central_Result>("sp_vDM2_1_24hour_Central");
        }
    
        public virtual ObjectResult<sp_vDM2_1_24hour_Central_2_Result> sp_vDM2_1_24hour_Central_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM2_1_24hour_Central_2_Result>("sp_vDM2_1_24hour_Central_2");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_Central_Result> sp_vDM4_3_1min_Central()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_Central_Result>("sp_vDM4_3_1min_Central");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD34_Result> sp_vDM4_3_1min_POD34()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD34_Result>("sp_vDM4_3_1min_POD34");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD35_Result> sp_vDM4_3_1min_POD35()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD35_Result>("sp_vDM4_3_1min_POD35");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD41_Result> sp_vDM4_3_1min_POD41()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD41_Result>("sp_vDM4_3_1min_POD41");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD42_Result> sp_vDM4_3_1min_POD42()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD42_Result>("sp_vDM4_3_1min_POD42");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD43_Result> sp_vDM4_3_1min_POD43()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD43_Result>("sp_vDM4_3_1min_POD43");
        }
    
        public virtual ObjectResult<sp_vDM4_3_1min_POD44_Result> sp_vDM4_3_1min_POD44()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_1min_POD44_Result>("sp_vDM4_3_1min_POD44");
        }
    
        public virtual ObjectResult<sp_vDM4_3_24hour_Central_Result> sp_vDM4_3_24hour_Central()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_24hour_Central_Result>("sp_vDM4_3_24hour_Central");
        }
    
        public virtual ObjectResult<sp_vDM4_3_24hour_Central_2_Result> sp_vDM4_3_24hour_Central_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vDM4_3_24hour_Central_2_Result>("sp_vDM4_3_24hour_Central_2");
        }
    
        public virtual ObjectResult<sp_vFGO_1Hour_Table_1_Result> sp_vFGO_1Hour_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vFGO_1Hour_Table_1_Result>("sp_vFGO_1Hour_Table_1");
        }
    
        public virtual ObjectResult<sp_vFGO_1Minute_Table1_Result> sp_vFGO_1Minute_Table1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vFGO_1Minute_Table1_Result>("sp_vFGO_1Minute_Table1");
        }
    
        public virtual ObjectResult<sp_vFGO_1Minute_Table2_Result> sp_vFGO_1Minute_Table2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vFGO_1Minute_Table2_Result>("sp_vFGO_1Minute_Table2");
        }
    
        public virtual ObjectResult<sp_vFGO_24Hour_Table1_Result> sp_vFGO_24Hour_Table1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vFGO_24Hour_Table1_Result>("sp_vFGO_24Hour_Table1");
        }
    
        public virtual ObjectResult<sp_vFGO_24Hour_Table2_Result> sp_vFGO_24Hour_Table2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vFGO_24Hour_Table2_Result>("sp_vFGO_24Hour_Table2");
        }
    
        public virtual ObjectResult<sp_vLMD_1Hour_Table_1_Result> sp_vLMD_1Hour_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vLMD_1Hour_Table_1_Result>("sp_vLMD_1Hour_Table_1");
        }
    
        public virtual ObjectResult<sp_vLMD_1Hour_Table_2_Result> sp_vLMD_1Hour_Table_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vLMD_1Hour_Table_2_Result>("sp_vLMD_1Hour_Table_2");
        }
    
        public virtual ObjectResult<sp_vLMD_1Minute_Table_1_Result> sp_vLMD_1Minute_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vLMD_1Minute_Table_1_Result>("sp_vLMD_1Minute_Table_1");
        }
    
        public virtual ObjectResult<sp_vLMD_24Hour_Table_1_Result> sp_vLMD_24Hour_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vLMD_24Hour_Table_1_Result>("sp_vLMD_24Hour_Table_1");
        }
    
        public virtual ObjectResult<sp_vLMD_24Hour_Table_2_Result> sp_vLMD_24Hour_Table_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vLMD_24Hour_Table_2_Result>("sp_vLMD_24Hour_Table_2");
        }
    
        public virtual ObjectResult<sp_vOLD_1Hour_Table_1_Result> sp_vOLD_1Hour_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vOLD_1Hour_Table_1_Result>("sp_vOLD_1Hour_Table_1");
        }
    
        public virtual ObjectResult<sp_vOLD_1Hour_Table_2_Result> sp_vOLD_1Hour_Table_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vOLD_1Hour_Table_2_Result>("sp_vOLD_1Hour_Table_2");
        }
    
        public virtual ObjectResult<sp_vOLD_1Minute_Table_1_Result> sp_vOLD_1Minute_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vOLD_1Minute_Table_1_Result>("sp_vOLD_1Minute_Table_1");
        }
    
        public virtual ObjectResult<sp_vOLD_24Hour_Table_1_Result> sp_vOLD_24Hour_Table_1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vOLD_24Hour_Table_1_Result>("sp_vOLD_24Hour_Table_1");
        }
    
        public virtual ObjectResult<sp_vOLD_24Hour_Table_2_Result> sp_vOLD_24Hour_Table_2()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_vOLD_24Hour_Table_2_Result>("sp_vOLD_24Hour_Table_2");
        }
    
        public virtual int spUtil_ReIndexDatabase_UpdateStats()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUtil_ReIndexDatabase_UpdateStats");
        }
    
        public virtual int GetKws2016()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("GetKws2016");
        }
    
        public virtual int myUpdDataSP2016(Nullable<int> myyearParam)
        {
            var myyearParamParameter = myyearParam.HasValue ?
                new ObjectParameter("myyearParam", myyearParam) :
                new ObjectParameter("myyearParam", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("myUpdDataSP2016", myyearParamParameter);
        }
    }
}
