//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM2_1_24hour_Central
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> POD41_BD { get; set; }
        public Nullable<double> POD42_BD { get; set; }
        public Nullable<double> POD43_BD { get; set; }
        public Nullable<double> POD44_BD { get; set; }
        public Nullable<double> POD41_DAILY_MANURE { get; set; }
        public Nullable<double> POD42_DAILY_MANURE { get; set; }
        public Nullable<double> POD43_DAILY_MANURE { get; set; }
        public Nullable<double> POD44_DAILY_MANURE { get; set; }
        public Nullable<double> TOTAL_FT_GC_YESTERDAY { get; set; }
        public Nullable<double> TOTAL_FT_GF_YESTERDAY { get; set; }
        public Nullable<double> COGEN1_TOTALKWH_ACT { get; set; }
        public Nullable<double> COGEN1_TOTALHOURS_ACT { get; set; }
        public Nullable<double> COGEN2_TOTALKWH_ACT { get; set; }
        public Nullable<double> COGEN2_TOTALHOURS_ACT { get; set; }
        public Nullable<double> DELTA_VOLUME_BIODOME { get; set; }
    }
}
