//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vDM4_3_24hour_Central_2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> DELTA_VOLUME_BIODOME { get; set; }
        public Nullable<double> TOTAL_GAS_COGEN_YESTERDAY { get; set; }
    }
}
