//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFGO_24Hour_Table1
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> EV3_DAILY_LOG { get; set; }
        public Nullable<double> EV4_DAILY_LOG { get; set; }
        public Nullable<double> MF3_DAILY_LOG { get; set; }
        public Nullable<double> MF4_DAILY_LOG { get; set; }
        public Nullable<double> VC4_DAILY_LOG { get; set; }
        public Nullable<double> VC5_DAILY_LOG { get; set; }
        public Nullable<double> VC6_DAILY_LOG { get; set; }
        public Nullable<double> VC7_DAILY_LOG { get; set; }
        public Nullable<double> DELTA_VOLUME_BIODOME { get; set; }
    }
}
