//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFGO_1Minute_Table2
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> LT_RP_EU { get; set; }
        public Nullable<double> LT_L1_1_EU { get; set; }
        public Nullable<double> LT_L1_2_EU { get; set; }
        public Nullable<double> LT_L2_1_EU { get; set; }
        public Nullable<double> LT_L2_2_EU { get; set; }
        public Nullable<double> TT_G2_EU { get; set; }
        public Nullable<double> TT_OT_EU { get; set; }
        public Nullable<double> TT_RP_EU { get; set; }
        public Nullable<double> TT_GF_EU { get; set; }
        public Nullable<double> IT_E1_EU { get; set; }
        public Nullable<double> IT_E2_EU { get; set; }
        public Nullable<double> MODBUS_COGEN_PWROUT_ACT { get; set; }
    }
}
