//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLMD_1Hour_Table_1
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> PT_CA_EU { get; set; }
        public Nullable<double> TT_H1_1_EU { get; set; }
        public Nullable<double> TT_H1_2_EU { get; set; }
        public Nullable<double> TT_H1_3_EU { get; set; }
        public Nullable<double> TT_H1_4_EU { get; set; }
        public Nullable<double> TT_H2_1_EU { get; set; }
        public Nullable<double> TT_H2_2_EU { get; set; }
        public Nullable<double> TT_H2_3_EU { get; set; }
        public Nullable<double> TT_H2_4_EU { get; set; }
        public Nullable<double> TT_HZ_1_EU { get; set; }
        public Nullable<double> TT_HZ_2_EU { get; set; }
    }
}
