//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Affinity.Helper.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class vLMD_1Minute_Table_1
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> DateStr { get; set; }
        public Nullable<double> PT_G1_EU { get; set; }
        public Nullable<double> PT_G2_EU { get; set; }
        public Nullable<double> FT_L_1_EU { get; set; }
        public Nullable<double> FT_L_2_EU { get; set; }
        public Nullable<double> FT_G1_EU { get; set; }
        public Nullable<double> FT_CHP_EU { get; set; }
        public Nullable<double> FT_GF_EU { get; set; }
        public Nullable<double> PX { get; set; }
        public Nullable<double> VT_GT { get; set; }
        public Nullable<double> PT_GT_EU { get; set; }
        public Nullable<double> FT_G2_EU { get; set; }
        public Nullable<double> LT_ES_EU { get; set; }
        public Nullable<double> LT_RP_EU { get; set; }
    }
}
